### ISSUE TITLE
Material-Theme in new Version

### ISSUE THREAD

**Issue by Springrbua** [appreciated/vaadin-app-layout#249] opened 2019-04-05 07:43 UTC
### Describe the bug
The style of the Material Theme is not correct in the new Version (2.1.0.alpha1 and current Master)

### To Reproduce
1. Add `@Theme(Material.class)` in `com.github.appreciated.app.layoutMainLayout` of the app-layout-demo.
2. Run the application

### Screenshots

**App Drawer**
![image](https://user-images.githubusercontent.com/18258317/55611839-035ae200-5787-11e9-834e-d7bf3d4c0cfa.png)

**Ripple effect on click:**
![image](https://user-images.githubusercontent.com/18258317/55611859-179edf00-5787-11e9-8406-7859bcb9d089.png)

**Notifications:**
![image](https://user-images.githubusercontent.com/18258317/55611881-25ecfb00-5787-11e9-827d-fc0036dfacb3.png)

**Comment by appreciated** [comment] 2019-04-05 08:01
I don't understand what the problem is, this looks beautiful 😅.

**Comment by appreciated** [comment] 2019-04-05 09:50
Most of the issues should have been fixed by 4568559428ffbe2ce92797e00de1b3f73c56fdfb. Dark still has some major issues.

**Comment by appreciated** [comment] 2019-04-06 09:56
fixed by 1ec458cbf4d248cebce8748eefddedd44ca41e2d

**Closed by appreciated** 2019-04-06 09:56 UTC
Labels: bug
