### ISSUE TITLE
iOS scrolling behaviour

### ISSUE THREAD

**Issue by marsenman** [appreciated/vaadin-app-layout#250] opened 2019-04-05 12:38 UTC
**Describe the bug**
I am using the LEFT_RESPONSIVE_HYBRID_NO_APP_BAR in a Vaadin 13 app. The scrolling of content is smooth on android devices but this smoothness is missing on iOS devices. I can reproduce it on the [demo page](https://appreciated-collection.herokuapp.com/app-layout/) with an iphone 6s and 7.
But it's ok on the [demo page](https://polymerelements.github.io/app-layout/templates/getting-started/) of the underlying app layout component.

1. Open Demo on iOS device
2. Scrolling content is not smooth

**Expected behavior**
Smooth scrolling on iOS like on android.

** Additional Information (please complete the following information):**
 - OS: iOS 12.2
 - Browser: chrome, safari
 - Version: 2.08

**Comment by appreciated** [comment] 2019-04-06 08:44
Since I do not own an iOS device there is not much I can do to fix this, I will need the cause of the issue to fix this. 
Can you check if this [codepen](https://codepen.io/chriscoyier/pen/nHEDj) has similar issues?

**Comment by marsenman** [comment] 2019-04-08 08:04
I have checked it with my iPhone and it's ok at this codepen.

**Comment by cedricaebi** [comment] 2019-04-09 11:51
I'm experiencing the same issue (up to 2.1.0beta1). It works with every other browser expect Safari mobile and also Chrome for iOS. Safari for Mac works fine too. I can't really debug it in the iPhone simulator, but I think it has something to do with the app layout content overlapping with something, because when you scroll down to the bottom then up again a white space appears. Then the scrolling appears to be till this white space (which is not smooth). When you scroll on this whitespace the scrolling is smooth.
Hope this helps.

<img width="413" alt="Bildschirmfoto 2019-04-09 um 13 37 11" src="https://user-images.githubusercontent.com/48714215/55798146-86a16e00-5ace-11e9-9d00-0057df8a0ae4.png">

<img width="426" alt="Bildschirmfoto 2019-04-09 um 13 48 16" src="https://user-images.githubusercontent.com/48714215/55798050-44782c80-5ace-11e9-87c5-8b24addbd840.png">

**Comment by cedricaebi** [comment] 2019-04-16 12:25
I found a "semi-solution" for the smooth scrolling and white-space. Apply 
`body {
      -webkit-overflow-scrolling: touch;
       position: absolute;
 }`

This will let you scroll smooth on everything, and the body doesn't leave this ugly white space.

But this solution has some problems:
The body will still overlap with some things when you scroll and hold. 
And sometimes the scroll action focuses on the wrong element

**Comment by appreciated** [comment] 2019-04-16 13:08
@cedricaebi I will need to get a hand on an ios device, otherwise I will nor really be able to fix this.

**Comment by cedricaebi** [comment] 2019-04-16 13:15
@appreciated sure thing. I use XCode with the built-in simulator for iOS devices, but that means of course that you need a Mac (which you may have).

**Comment by appreciated** [comment] 2019-04-17 16:28
@marsenman and @cedricaebi I managed to fix this issue, I just need to bring it to all behaviours.

**Comment by appreciated** [comment] 2019-04-20 14:13
Closed by 495a077787bb129ba9a32faea2c189e90131015f

**Closed by appreciated** 2019-04-20 14:13 UTC
Labels: bug

**Comment by appreciated** [comment] 2019-04-20 14:51
An preview of this fix is available in [2.1.1.beta1](https://vaadin.com/directory/component/app-layout-add-on/2.1.1.beta1) and [3.0.0.beta3](https://vaadin.com/directory/component/app-layout-add-on/3.0.0.beta3). Please checkout if this works for you!

**Comment by cedricaebi** [comment] 2019-04-24 07:13
@appreciated Works like a charm for me now! Now white spaces and smooth scrolling as it should be. Thank you so much!
