### ISSUE TITLE
the styles do not work on the tomcat server (app-toolbar) - app with spring boot

### ISSUE THREAD

**Issue by Sergio70** [appreciated/vaadin-app-layout#157] opened 2018-10-12 04:00 UTC
Hi good day.

I have done several tests, for me to solve this but I could not, have you any solution for this problem? I attached the images of how it is shown in the ide eclipse and on the tomcat server

I am using springboot (https://vaadin.com/start/lts/project-base-spring).
sorry for my English.

run In IDE eclipce

![image](https://user-images.githubusercontent.com/20112231/46846964-a1a55680-cda7-11e8-9117-01bdcd03f98e.png)

run In server tomcat with war generate
![image](https://user-images.githubusercontent.com/20112231/46847309-4d9b7180-cda9-11e8-9404-7001a47ca414.png)

**Comment by appreciated** [comment] 2018-10-12 07:50
Hi this issue is a duplicate of #153 please consider closing this one.

**Comment by appreciated** [comment] 2018-10-12 11:33
Could you please try to use the jetty spring boot dependencies (instead of the default Tomcat dependencies) and check if it makes a difference?

**Comment by deyaeddin** [comment] 2018-10-20 01:36
He @Sergio70 
You are using a Base Spring project which dose not **extends SpringBootServletInitializer**

make your Application Class:

```
@SpringBootApplication
public class Application extends SpringBootServletInitializer{

	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}

	@Override
	protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
		return application.sources(Application.class);
	}
}
```
also, you might need to add Custom Servlet Initializer ( Optional but recommended )
something like ...

```
@SpringComponent
public class CustomVaadinServlet extends SpringServlet implements VaadinServiceInitListener {

	public CustomVaadinServlet(ApplicationContext context) {
		super(context);
	}
	@Override
	public void serviceInit(ServiceInitEvent event) {
		event.addBootstrapListener(new CustomBootstrapListener());
	}
}
```
```
public class CustomBootstrapListener implements BootstrapListener {
	@Override
	public void modifyBootstrapPage(BootstrapPageResponse response) {

		final Element head = response.getDocument().head();
		// Add service worker
		head.append("<script>if ('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js')</script>");

		// add icons tags
		head.append("<link rel='shortcut icon' href='icons/favicon.ico'>");
		head.append("<link rel='icon' sizes='192x192' href='icons/icon-192.png'>");
		head.append("<link rel='icon' sizes='96x96' href='icons/icon-96.png'>");
		head.append("<link rel='apple-touch-icon' sizes='180x180' href='icons/apple-icon-180x180.png'>");
		head.append("<link rel='apple-touch-icon' sizes='114x114' href='icons/apple-icon-114x114.png'>");
	}
}
```

**Comment by Sergio70** [comment] 2018-10-24 00:43
After a lot of research, I found the problem, the problem is one of my complements that I have in my project. that works incorrectly with the vaadin-app-layout and my components created with web components, pdf-browser is the component that creates the problem.
Thanks to the two for the help :).
regards.

**Closed** 2018-10-24 03:33 UTC
