### ISSUE TITLE
Maven: Failed to collect dependencies

### ISSUE THREAD

**Issue by vrepetenko** [appreciated/vaadin-app-layout#199] opened 2018-12-24 09:26 UTC
**Describe the bug**
Failed to collect dependencies at com.github.appreciated:app-layout-addon:jar:2.0.1
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact com.github.appreciated:app-layout-root:pom:2.0.1-SNAPSHOT in vaadin-addons (http://maven.vaadin.com/vaadin-addons)

**To Reproduce**

Add dependency to pom.xml:
<dependency>
   <groupId>com.github.appreciated</groupId>
   <artifactId>app-layout-addon</artifactId>
   <version>2.0.1</version>
</dependency>

Run maven: 
mvn clean install -X -U

**Expected behavior**
app-layout-addon dependencies resolved

**Screenshots**
NA

** Additional Information (please complete the following information):**
mvn -version
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-18T02:33:14+08:00)
Maven home: /opt/local/apache-maven
Java version: 1.8.0_191, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre
Default locale: en_RU, platform encoding: UTF-8

**Comment by appreciated** [comment] 2018-12-24 09:36
Probalby a duplicate of #198

**Comment by appreciated** [comment] 2018-12-24 09:40
I stopped the Release and I'll see if I can fix it asap

**Closed** 2018-12-24 17:33 UTC
Labels: bug

**Comment by appreciated** [comment] 2018-12-24 17:35
2.0.2 is now in the shelves!

**Comment by vrepetenko** [comment] 2018-12-25 01:20
Thanks!

**Comment by ChristianStrotz** [comment] 2018-12-25 13:42
Thanks a lot!
